import pandas as pd
import sys
import warnings
from utils.LoadData import loadfile
from utils.AspectDataset import generate_aspect_dataset
from modules.ABSA import aspect_sentiment_analysis
from modules.ML_Sentiment import train_ml_model
from modules.DL_Intent import classify_intent

# Suppress pandas warnings for cleaner output
warnings.simplefilter(action='ignore', category=FutureWarning)


def load_and_prepare_data():
    """
    Handles loading the main data.csv file and performing initial prep.
    """
    print("\n--- Step 1: Loading and Preparing Data ---")
    try:
        df = loadfile("data/data.csv")
    except FileNotFoundError:
        print("Error: 'data/data.csv' not found. Please place it in the 'data' folder.")
        return None
        
    print(f"Loaded {len(df)} reviews.")
    
    if 'Summary' not in df.columns:
        print("Error: 'Summary' column not found in data.csv.")
        return None
        
    # Ensure 'Summary' column is clean for processing
    df.dropna(subset=["Summary"], inplace=True)
    df["Summary"] = df["Summary"].astype(str)
    return df


def run_model_1_absa(df):
    """
    Runs the Transformer ABSA (Model 1) and generates the aspect dataset
    which is required for training Model 2.
    """
    print("\n--- Step 2: Running Transformer ABSA (Model 1) ---")
    if df is None:
        print("Cannot run Model 1: Data frame is empty.")
        return None, None
        
    df = aspect_sentiment_analysis(df)
    
    print("Generating aspect dataset from Model 1 results...")
    aspect_df = generate_aspect_dataset(df)
    print(f"Generated {len(aspect_df)} aspect-sentiment entries.")
    
    return df, aspect_df


def run_model_2_ml_training(aspect_df):
    """
    Trains the Machine Learning Sentiment Model (Model 2)
    using the data generated by Model 1.
    """
    print("\n--- Step 3: Training ML Sentiment Model (Model 2) ---")
    if aspect_df is None or aspect_df.empty:
        print("Skipping ML Model training: No aspect data was provided (run Model 1 first).")
        return
        
    train_ml_model()


def run_model_3_dl_intent(df):
    """
    Runs the Deep Learning Intent Checker (Model 3) on a sample
    of the original data.
    """
    print("\n--- Step 4: Running DL Intent Checker (Model 3) ---")
    if df is None or df.empty:
        print("Skipping DL Intent Checker: No data frame provided.")
        return

    try:
        # Get a sample of 50 non-empty summaries
        summary_sample = df[df['Summary'].str.len() > 10].sample(50)['Summary'].tolist()
        
        if summary_sample:
            classify_intent(summary_sample)
        else:
            print("Could not get a valid sample of summaries to classify.")
    except ValueError:
        print(f"Not enough data to sample for intent classification (need at least 5 reviews).")
    except Exception as e:
        print(f"Error sampling summaries: {e}")


if __name__ == "__main__":
    print("--- NLP Project Start ---")
    
  
    main_df = load_and_prepare_data()
    
    if main_df is not None:
        
        # --- Model 1: Transformer ABSA ---
        # keep on, as Model 2 depends on it
        # This model reads reviews and finds aspect sentiments.
        # It also creates the 'aspect_data.csv' file needed for Model 2.
        main_df, aspect_df = run_model_1_absa(main_df)
        


        # --- Model 2: ML Sentiment Training ---

        # This model TRAINS a Logistic Regression model on 'aspect_data.csv'.
        
        # run_model_2_ml_training(aspect_df)
        


        # --- Model 3: DL Intent Checker ---

        # This model USES a pre-trained DL model to classify 50 sample reviews.
        
        # run_model_3_dl_intent(main_df)
        
    else:
        print("Failed to load data. Exiting.")

    print("\n--- Project End ---")